-- Create support data

-- Version 2

DROP table DL_CRM.NL_SUPP_JAN2017_APR2018;
DROP table DL_CRM.NL_SUPP_JAN2017_APR2018_DETAILS;

create multiset table DL_CRM.NL_SUPP_JAN2017_APR2018_DETAILS
as
(
SELECT
a.*,
b.CASE_START_DTTM,
b.CASE_END_DTTM,
(CAST((CAST(b.CASE_END_DTTM AS DATE)- CAST(b.CASE_START_DTTM AS DATE)) AS DECIMAL(18,6)) * 60*60*24)
      + ((EXTRACT(  HOUR FROM b.CASE_END_DTTM) - EXTRACT(  HOUR FROM b.CASE_START_DTTM)) * 60*60)
      + ((EXTRACT(MINUTE FROM b.CASE_END_DTTM) - EXTRACT(MINUTE FROM b.CASE_START_DTTM)) * 60)
      +  (EXTRACT(SECOND FROM b.CASE_END_DTTM) - EXTRACT(SECOND FROM b.CASE_START_DTTM)) AS CASE_PROC_TIME_SEC,
CAST(CASE_PROC_TIME_SEC / 60 AS INTEGER) AS CASE_PROC_TIME_MIN,
CAST(CASE_PROC_TIME_SEC / 3600 AS INTEGER) CASE_PROC_TIME_HR,
CAST(CASE_PROC_TIME_SEC / 86400 AS INTEGER) AS CASE_PROC_TIME_DAY
FROM (
SELECT
*
FROM 
(SELECT
NORTON_ACCT_GUID,
CASE_ID,
CID,
SRC_DT,
REC_DTTM,
REC_DTTM_PST,
CNTCT_TYPE_CD,
/* CUST_EML_ID,
CUST_FST_NM,
CUST_LST_NM, */
PROD_NM,
PROD_VERS_NUM,
CASE_STS_CD,
CASE_SUB_STS_CD,
CASE_ORIG_TXT,
CASE_TYPE_CD,
PROB_DESC,
CTRY_NM,
LANG_CD,
RMTE_ASST_USED_IN,
OUTB_CALL_TYPE_CD,
PROD_LANG_CD,
OPRT_SYS_NM,
IS_AUTO_CRT_CASE_IN,
CASE_MOD_RSN_CD,
PRIM_ISS_TYPE_CD,
PRIM_ISS_SBTYP_CD,
PRIM_ISS_CMBN_TYPE_CD,
PRIM_SOLUT_TYPE_CD,
PRIM_SOLUT_SBTYP_CD,
PRIM_SOLUT_CMBN_TYPE_CD,
ROW_NUMBER () OVER (PARTITION BY CASE_ID, NORTON_ACCT_GUID ORDER BY REC_DTTM_PST DESC) AS RN
FROM  EDW_KATAMARI_V.cntct_case
WHERE
CAST(SRC_DT as date) >= '2017-01-01' 
AND CAST(SRC_DT as date)  < '2018-05-01'  
AND CASE_ID is not null
AND NORTON_ACCT_GUID is not null
AND PROD_NM <> 'LifeLock'
) c
WHERE
RN = 1 ) a
LEFT JOIN
(
SELECT
CASE_ID,
NORTON_ACCT_GUID,
MIN(REC_DTTM_PST) AS CASE_START_DTTM,
MAX(REC_DTTM_PST) AS CASE_END_DTTM
FROM  EDW_KATAMARI_V.cntct_case
WHERE
CAST(SRC_DT as date) >= '2017-01-01' 
AND CAST(SRC_DT as date)  < '2018-05-01'  
AND CASE_ID is not null
AND NORTON_ACCT_GUID is not null
AND PROD_NM <> 'LifeLock'
GROUP BY
CASE_ID,
NORTON_ACCT_GUID
) b
ON a.CASE_ID = b.CASE_ID AND a.NORTON_ACCT_GUID = b.NORTON_ACCT_GUID
) WITH DATA PRIMARY INDEX (CID, NORTON_ACCT_GUID, CASE_ID)
;

ALTER TABLE DL_CRM.NL_SUPP_JAN2017_APR2018 DROP RN;
ALTER TABLE DL_CRM.NL_SUPP_JAN2017_APR2018_DETAILS DROP RN;

/* SELECT
SUM(PERC)
FROM ( */
SELECT
   COUNT(*),  
/*  COUNT(distinct NORTON_ACCT_GUID)   */
/*      TOP 10
*      */
/*  CTRY_NM, */
  PRIM_ISS_TYPE_CD 
 /* PRIM_ISS_CMBN_TYPE_CD */
/*  PRIM_ISS_SBTYP_CD */
/* PROD_NM */
/* CASE_ORIG_TXT, */
/* CNTCT_TYPE_CD, */
/* 100.00 * COUNT(*) / SUM(COUNT(*)) OVER () AS PERC  */
/* 100.00 * COUNT(distinct NORTON_ACCT_GUID) / SUM(COUNT(distinct NORTON_ACCT_GUID)) OVER () AS PERC  */
/* FROM DL_CRM.NL_SUPP_JAN2017_APR2018 */
FROM DL_CRM.NL_SUPP_JAN2017_APR2018_DETAILS
  WHERE 
  PROD_NM = 'LifeLock'
/* CASE_ID = '34265865'  */
/* PRIM_ISS_CMBN_TYPE_CD = 'Other Unlisted Issue' */
 GROUP BY 
/*  PROD_NM */
 PRIM_ISS_TYPE_CD 
/* PRIM_ISS_SBTYP_CD */
/* PRIM_ISS_CMBN_TYPE_CD */
/* CASE_ORIG_TXT */
/*  CNTCT_TYPE_CD */
/* CTRY_NM */
 ORDER BY
PERC DESC 
/* ) a
; */


DROP TABLE DL_CRM.NL_SUPP_JAN2017_APR2018_DETAILS_MOSTRECENT;

create multiset table DL_CRM.NL_SUPP_JAN2017_APR2018_DETAILS_MOSTRECENT
as
(
SELECT
b.*,
CASE WHEN b.NORTON_ACCT_GUID = CAST(c.ACCOUNT_GUID as VARCHAR(75)) THEN 1 ELSE 0 END AS LL_MATCH_IND
FROM (
SELECT
a.*
FROM DL_CRM.NL_SUPP_JAN2017_APR2018_DETAILS a
WHERE 
CTRY_NM = 'United States'
QUALIFY ROW_NUMBER() OVER(PARTITION BY NORTON_ACCT_GUID ORDER BY REC_DTTM_PST DESC) = 1
) b
LEFT JOIN
(
SELECT
DISTINCT ACCOUNT_GUID
FROM DL_CRM.LL_MATCH2
WHERE
MATCH_STRENGTH_CAT in ('Actual', 'High')
) c ON b.NORTON_ACCT_GUID = CAST(c.ACCOUNT_GUID as VARCHAR(75))
) WITH DATA PRIMARY INDEX (CID, NORTON_ACCT_GUID, CASE_ID)
;

SELECT
TOP 10
*
/*  COUNT(*),
COUNT(distinct NORTON_ACCT_GUID)  */
/* AVG(LL_MATCH_IND) */
FROM DL_CRM.NL_SUPP_JAN2017_APR2018_DETAILS_MOSTRECENT
WHERE
PRIM_SOLUT_TYPE_CD = 'Not Solved'
;

-- Version 1


create multiset table DL_CRM.NL_SUPP_JAN2017_APR292018
as
(
SELECT 
/* top 10 */
CASE_ID, 
max(CID) as CID, 
max(NORTON_ACCT_GUID) as NORTON_ACCT_GUID, 
min(CAST(SRC_DT as date)) as CASE_MIN_DT, 
max(CAST(SRC_DT as date)) as CASE_MAX_DT, 
max(PRIM_ISS_TYPE_CD) as PRIM_ISS_TYPE_CD, 
max(PRIM_ISS_SBTYP_CD) as PRIM_ISS_SBTYP_CD,
max(PRIM_SOLUT_TYPE_CD) as PRIM_SOLUT_TYPE_CD,
max(PRIM_SOLUT_SBTYP_CD) as PRIM_SOLUT_SBTYP_CD
FROM  EDW_KATAMARI_V.cntct_case a 
WHERE
CAST(SRC_DT as date) >= '2017-01-01' 
AND CASE_ID is not null
AND CAST(SRC_DT as date)  <= '2018-04-29'  
/* AND a.CASE_MOD_RSN_CD = 'Agent Edited' */
GROUP BY
CASE_ID
) WITH DATA PRIMARY INDEX (CID, NORTON_ACCT_GUID)
;


DROP TABLE DL_CRM.NL_SUPP_JAN2017_APR292018
;

SELECT
/* * */
/* TOP 100 */
/*  *  */
CASE_ID,
CID,
SRC_DT,
REC_DTTM,
REC_DTTM_PST,
MIN(REC_DTTM_PST) OVER (PARTITION BY CASE_ID, NORTON_ACCT_GUID ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS CASE_START_DTTM,
MAX(REC_DTTM_PST) OVER (PARTITION BY CASE_ID, NORTON_ACCT_GUID ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS CASE_END_DTTM,
CNTCT_TYPE_CD,
CUST_EML_ID,
/* CUST_PHN_NUM, */
CUST_FST_NM,
CUST_LST_NM,
PROD_NM,
PROD_VERS_NUM,
CASE_STS_CD,
CASE_SUB_STS_CD,
CASE_ORIG_TXT,
CASE_TYPE_CD,
PROB_DESC,
CTRY_NM,
LANG_CD,
RMTE_ASST_USED_IN,
/* RMTE_ASST_STS_DESC, */
OUTB_CALL_TYPE_CD,
/* BRWSR_NM, */
PROD_LANG_CD,
OPRT_SYS_NM,
/* OPRT_SYS_LANG,
OPRT_SYS_SRVC_PACK, */
IS_AUTO_CRT_CASE_IN,
NORTON_ACCT_GUID,
/* CUST_PERCEPTION_TXT, */
CASE_MOD_RSN_CD,
PRIM_ISS_TYPE_CD,
PRIM_ISS_SBTYP_CD,
PRIM_ISS_CMBN_TYPE_CD,
/* PRIM_ISS_DTLS_DESC,  */
PRIM_SOLUT_TYPE_CD,
PRIM_SOLUT_SBTYP_CD,
PRIM_SOLUT_CMBN_TYPE_CD
/* PRSN_MOBL_PHN_NUM,
PRSN_OTH_PHN_NUM */
FROM 
EDW_KATAMARI_V.cntct_case
/* DL_CRM.NL_SUPP_JAN2017_APR292018 */
 WHERE
/*  OUTB_CALL_TYPE_CD = 'Outbound' */
/* NORTON_ACCT_GUID = '170057163577694232016874789541377625' 
GROUP BY
NORTON_ACCT_GUID
HAVING COUNT(*) > 1 */
/* A.PRIM_SOLUT_TYPE_CD is not null
AND
A.PRIM_ISS_TYPE_CD is null */
CASE_ID = '34265865'
QUALIFY ROW_NUMBER () OVER (PARTITION BY CASE_ID, NORTON_ACCT_GUID ORDER BY REC_DTTM_PST DESC) = 1
ORDER BY
REC_DTTM_PST DESC
;



SELECT
COUNT(distinct ACCOUNT_GUID)
FROM DL_CRM.LL_MATCH3
WHERE
MATCH_STRENGTH_CAT = 'High'
AND
LL_ACTIVE_FLG = 1

SELECT
COUNT(distinct NORTON_ACCT_GUID)
FROM EDW_KATAMARI_V.cntct_case
WHERE
NORTON_ACCT_GUID is not null

SELECT
MIN(SRC_DT)
FROM (
SELECT
SRC_DT
FROM EDW_KATAMARI_V.cntct_case
WHERE
CTRY_NM = 'United States'
AND
SRC_DT is not null
AND
NORTON_ACCT_GUID is not null
) a;


SELECT
TOP 10
*
FROM DL_NBU.ipa_demo_norton3
;


SELECT
TOP 10
ACCOUNT_GUID
,EMAIL_ADDRESS
,COUNTRY_CODE
,COUNTRY_NAME
,REGION
,TERRITORY
,ACCOUNT_CREATE_DATE
,CURRENT_SUB_CHANNEL
,SUBSCRIPTION_STATUS
,EMAIL_OPT_OUT
,CURRENT_AR_FLAG
,CURRENT_EXPIRATION_DATE
,ACTIVE_PRODUCTS
,LAST_INTERACTION_DATE
,FIRST_INTERACTION_DATE
,LAST_INTERACTION_SOURCE
,PAID_STATUS
,ETL_UPDATE_DTTM
FROM CDCBVDB.BV_MT_REG_ACCT_DTLS
WHERE 
 PAID_STATUS = 'PAID'
AND
SUBSCRIPTION_STATUS = 'ACTIVE' 
AND
ACCOUNT_GUID in (
 -606527603655483782604284462276235403
/* ,83398902169040272374112936522832937 */
)                                                              
;


-- 2018-05-25 run

DROP TABLE DL_CRM.NL_SUPP_DATA_PROFILE;

CREATE MULTISET TABLE DL_CRM.NL_SUPP_DATA_PROFILE
AS (
SELECT
a.*,
CASE WHEN TRIM(OREPLACE(CAST(a.NORTONGUID as varchar(75)), '.', '')) = b.NORTON_ACCT_GUID THEN 1 ELSE 0 END AS CONTACT_SUPP_IND,
CASE WHEN TRIM(OREPLACE(CAST(a.NORTONGUID as varchar(50)), '.', '')) = d.ACCOUNT_GUID THEN 1 ELSE 0 END AS LL_MATCH3_IND,
CASE WHEN a.NORTONGUID = e.ACCOUNT_GUID THEN 1 ELSE 0 END AS ACT_PD_IND,
c.Segment_Version2
FROM DL_NBU.ipa_demo_norton3 a
LEFT JOIN
(
SELECT
distinct
NORTON_ACCT_GUID
FROM EDW_KATAMARI_V.cntct_case
WHERE
PROD_NM <> 'LifeLock'
AND
NORTON_ACCT_GUID is not null
) b ON TRIM(OREPLACE(CAST(a.NORTONGUID as varchar(75)), '.', '')) = b.NORTON_ACCT_GUID
LEFT JOIN
(
SELECT
ACCOUNT_GUID,
MAX(Segment_Version2) as Segment_Version2
FROM dl_crm.mgua_ll_segmented_05092018
GROUP BY
ACCOUNT_GUID
) c ON a.NORTONGUID = c.ACCOUNT_GUID
LEFT JOIN
(
SELECT
DISTINCT ACCOUNT_GUID
FROM DL_CRM.LL_MATCH2
WHERE
MATCH_STRENGTH_CAT in ('Actual', 'High')
) d ON TRIM(OREPLACE(CAST(a.NORTONGUID as varchar(50)), '.', '')) = d.ACCOUNT_GUID
LEFT JOIN
(
SELECT
DISTINCT ACCOUNT_GUID
FROM CDCBVDB.BV_MT_REG_ACCT_DTLS
WHERE 
 PAID_STATUS = 'PAID'
AND
SUBSCRIPTION_STATUS = 'ACTIVE'
AND
ACCOUNT_GUID is not null
) e ON a.NORTONGUID = e.ACCOUNT_GUID
) WITH DATA PRIMARY INDEX(NORTONGUID)
;

SELECT
/* COUNT(*),
COUNT(distinct NORTONGUID) */
ACT_PD_IND,
LL_MATCH3_IND,
/*  CONTACT_SUPP_IND, */ 
/* AVG(LL_MATCH3_IND) */
AVG(CONTACT_SUPP_IND)
FROM DL_CRM.NL_SUPP_DATA_PROFILE
/* WHERE
ACT_PD_IND = 1 */
GROUP BY
ACT_PD_IND,
LL_MATCH3_IND
/* CONTACT_SUPP_IND */
;


SELECT
/*  TOP 10 
 *  */
/* ACCOUNT_GUID */
MATCH_STRENGTH_CAT,
COUNT(*),
COUNT(distinct ACCOUNT_GUID)
FROM DL_CRM.LL_MATCH2
GROUP BY
MATCH_STRENGTH_CAT
ACCOUNT_GUID
HAVING COUNT(*) > 1
WHERE
  ACCOUNT_GUID = '-276598721862328990649647341523620552'  
MATCH_STRENGTH_CAT = 'Low'
;